pro:
  push:
    - name: build_docker
      docker:
        image: oven/bun:1.2.19
        volumes:
          - /root/.bun/install/cache:cow
      stages:
        - name: 构建前端项目
          script:
            - bun install
            - bun run build
        - name: 构建镜像
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: 推送到制品库
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
