/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
  }
}
