-- 文件件/网络资源
CREATE TABLE folder_web (
  id CHAR(18) PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL DEFAULT '',
  `order` INTEGER NOT NULL DEFAULT 0
);
-- 网络资源
CREATE TABLE source_web (
  id CHAR(18) PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL DEFAULT '',
  `type` SMALLINT NOT NULL DEFAULT 0,
  favicon VARCHAR(255) NOT NULL DEFAULT '',
  folder TEXT NOT NULL DEFAULT '',
  `order` INTEGER NOT NULL DEFAULT 0,
  props VARCHAR(1024) NOT NULL
);
-- 我的视频数据
CREATE TABLE my_video_item (
  id CHAR(18) PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `type` SMALLINT NOT NULL DEFAULT 0,
  `from` SMALLINT NOT NULL DEFAULT 0,
  payload VARCHAR(255) NOT NULL DEFAULT '',
  cover VARCHAR(255) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT ''
);